/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as ImperiosSlugRouteImport } from './routes/imperios/$slug'
import { Route as ImperiosNovoRouteImport } from './routes/imperios/novo'
import { Route as SquadsSlugRouteImport } from './routes/squads/$slug'
import { Route as SquadsNovoRouteImport } from './routes/squads/novo'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const ImperiosSlugRoute = ImperiosSlugRouteImport.update({
  id: '/imperios/$slug',
  path: '/imperios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImperiosNovoRoute = ImperiosNovoRouteImport.update({
  id: '/imperios/novo',
  path: '/imperios/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsSlugRoute = SquadsSlugRouteImport.update({
  id: '/squads/$slug',
  path: '/squads/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsNovoRoute = SquadsNovoRouteImport.update({
  id: '/squads/novo',
  path: '/squads/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/loja': typeof LojaRoute
  '/pagamento': typeof PagamentoRoute
  '/ranking': typeof RankingRoute
  '/reservar': typeof ReservarRoute
  '/imperios/$slug': typeof ImperiosSlugRoute
  '/imperios/novo': typeof ImperiosNovoRoute
  '/squads/$slug': typeof SquadsSlugRoute
  '/squads/novo': typeof SquadsNovoRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/loja': typeof LojaRoute
  '/pagamento': typeof PagamentoRoute
  '/ranking': typeof RankingRoute
  '/reservar': typeof ReservarRoute
  '/imperios/$slug': typeof ImperiosSlugRoute
  '/imperios/novo': typeof ImperiosNovoRoute
  '/squads/$slug': typeof SquadsSlugRoute
  '/squads/novo': typeof SquadsNovoRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/loja': typeof LojaRoute
  '/pagamento': typeof PagamentoRoute
  '/ranking': typeof RankingRoute
  '/reservar': typeof ReservarRoute
  '/imperios/$slug': typeof ImperiosSlugRoute
  '/imperios/novo': typeof ImperiosNovoRoute
  '/squads/$slug': typeof SquadsSlugRoute
  '/squads/novo': typeof SquadsNovoRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/loja'
    | '/pagamento'
    | '/ranking'
    | '/reservar'
    | '/imperios/$slug'
    | '/imperios/novo'
    | '/squads/$slug'
    | '/squads/novo'
    | '/api/public/mercadopago-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/loja'
    | '/pagamento'
    | '/ranking'
    | '/reservar'
    | '/imperios/$slug'
    | '/imperios/novo'
    | '/squads/$slug'
    | '/squads/novo'
    | '/api/public/mercadopago-webhook'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/loja'
    | '/pagamento'
    | '/ranking'
    | '/reservar'
    | '/imperios/$slug'
    | '/imperios/novo'
    | '/squads/$slug'
    | '/squads/novo'
    | '/api/public/mercadopago-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  LojaRoute: typeof LojaRoute
  PagamentoRoute: typeof PagamentoRoute
  RankingRoute: typeof RankingRoute
  ReservarRoute: typeof ReservarRoute
  ImperiosSlugRoute: typeof ImperiosSlugRoute
  ImperiosNovoRoute: typeof ImperiosNovoRoute
  SquadsSlugRoute: typeof SquadsSlugRoute
  SquadsNovoRoute: typeof SquadsNovoRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imperios/$slug': {
      id: '/imperios/$slug'
      path: '/imperios/$slug'
      fullPath: '/imperios/$slug'
      preLoaderRoute: typeof ImperiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imperios/novo': {
      id: '/imperios/novo'
      path: '/imperios/novo'
      fullPath: '/imperios/novo'
      preLoaderRoute: typeof ImperiosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads/$slug': {
      id: '/squads/$slug'
      path: '/squads/$slug'
      fullPath: '/squads/$slug'
      preLoaderRoute: typeof SquadsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads/novo': {
      id: '/squads/novo'
      path: '/squads/novo'
      fullPath: '/squads/novo'
      preLoaderRoute: typeof SquadsNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  LojaRoute: LojaRoute,
  PagamentoRoute: PagamentoRoute,
  RankingRoute: RankingRoute,
  ReservarRoute: ReservarRoute,
  ImperiosSlugRoute: ImperiosSlugRoute,
  ImperiosNovoRoute: ImperiosNovoRoute,
  SquadsSlugRoute: SquadsSlugRoute,
  SquadsNovoRoute: SquadsNovoRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
